### ISSUE TITLE
Some missing packets

### ISSUE THREAD

**Issue by Abisku** [cucksexy/growtopia-packets#1]
PACKET_SEND_PLAYER_TRIBUTE_DAT
PACKET_PVE_UNK1
PACKET_PVE_UNK2
PACKET_PVE_UNK3
PACKET_PVE_UNK4
PACKET_PVE_UNK5
PACKET_SET_EXTRA_MODS
PACKET_ON_STEP_ON_TILE_MOD
PACKET_ERRORTYPE

**Comment by notMrTour** [comment]
done
